### ISSUE TITLE
Up and running but no messages over the serial monitor from the ESP...

### ISSUE THREAD

**Issue by jonprogers** [MrPsi/NodeMCU-Wixel#7] opened 2016-05-28 14:32 UTC
Hi,

Thanks for this, it looks brilliant!!

I've just got this up and running, for now using an ESP8266-12e module rather than the whole NodeMCU development board, mainly as I had one lying around!!

Initially I had wifi connection issues getting error status 3 & 4 with the LED fast blinking - those appear to have gone away for now but once connected and I get the 'WiFi connected' message over the serial monitor the serial monitor just dies and I never get any of the other messages during operation.

It is all actually working as I'm getting the BGs coming up in Nightscout but I will have a problem if I ever have to start debugging anything. Just wanted to flag this was happening, NodeMCU on order to see if it's down to not following your instructions to the letter!!

Thanks for everything, your work here is really appreciated. I'm looking forward to being able to take more control of things as time goes by...

Cheers

Jon.

**Comment by MrPsi** [comment] 2016-05-28 17:24
Hi,

Glad you like it.

Error 3 means that access point is not found, and error 4 is just a general fail, do not know the cause.

If you want to get debug prints you can set "allowPrint = true" in modStart.lua. I disabled the prints by default because if xDrip tries to get data at the same time as the Wixel transfers data to the wifi module it might be an error. This is because the Wixel also uses the serial interface for transferring data to the wifi module.

**Comment by jonprogers** [comment] 2016-05-28 18:02
That's brilliant - thanks, have found the allowPrint flag with your
direction!

It's all breadboard and jumper wires at the moment so I'll be able to find
a better location for it when it all becomes a bit more permanent as the
wifi errors are intermittent at the moment, I've got other ESPs running
home automation and they all appear more stable when properly soldered
together!!

Cheers

Jon

_Jon Rogers_
07768 034738

**Comment by danpowell88** [comment] 2016-05-29 08:49
I had simiar issues with it freezing after a while, i changed the code to use the standard tx/rx ports and that seemed to fix it

**Closed as completed** 2016-06-02 18:08 UTC
